# Generated by Django 3.2.7 on 2021-09-14 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='owner',
            table='owner',
        ),
    ]
